baseURL = 'https://example.org/'
locale = 'en-US'
title = 'My New Hugo Site'

[security]
  allowContent = ['^text/(html|markdown|css|plain)$', '^application/json$']

[module]
  [module.hugoVersion]
    extended = true
    min = "0.165.0"
