# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = 'Piatto'
license = 'MIT'
licenselink = 'https://github.com/zentialEdwardSu/hugo-theme-piatto/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/zentialEdwardSu/hugo-theme-piatto'

# If you have a running demo of the theme
demosite = 'https://hugo-theme-piatto.edwardsu.me/'

# Taxonomy terms
tags = ['blog']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'EdwardSu'
  homepage = 'https://github.com/zentialEdwardSu'
