baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Piattos example site '
theme = "hugo-theme-piatto"
copyright = "EdwardSu ©"

[params]
  name = "EdwardSu"
  description = "Loafer and bug producer."
  initials = "Ed"
  footercd = true
  showReadingTime=true
  search = true # if show search bar
  recentPosts = true # if show recent posts
  recentPostsCount = 4

  [[params.social]]
    name = "Twitter"
    link = "#"
    icon = "ti ti-brand-x"

  [[params.social]]
    name = "Github"
    link = "#"
    icon = "ti ti-brand-github"
  
  [[params.social]]
    name = "Gitlab"
    link = "#"
    icon = "ti ti-brand-gitlab"

  [[params.social]]
    name = "Mail" 
    link = "#"
    icon = "ti ti-mail"

  [[params.social]]
    name = "LinkedIn"
    link = "#"
    icon = "ti ti-brand-linkedin"

[menu]
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Me"
    url = "/me/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true

  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1