#!/bin/bash

echo "Running pre-commit hooks"

TARGET_DIR="exampleSite/content/articles"

CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
SHOULD_ABORT=0
PROCESSED_FOLDERS=()

for FILE in $CHANGED_FILES; do
  if [[ $FILE == "$TARGET_DIR"*.typ ]]; then
    FOLDER_PATH=$(dirname "$FILE")
    
    # Check if the Folder already be processed
    if [[ ! " ${PROCESSED_FOLDERS[@]} " =~ " ${FOLDER_PATH} " ]]; then
      echo "Detected changes in $FOLDER_PATH"
      OUTPUT=$(python scripts/buildtyp.py -v -i "$FOLDER_PATH")
      
      if [ $? -eq 0 ]; then
        git add "$FOLDER_PATH"
        PROCESSED_FOLDERS+=("$FOLDER_PATH")
      else
        echo "Error: Python script failed for folder $FOLDER_PATH. Aborting commit."
        SHOULD_ABORT=1
        break
      fi
    fi
  fi
done

if [ $SHOULD_ABORT -eq 1 ]; then
  exit 1
fi

exit 0